[build]
  publish = "public"
  command = "npm run build"

[[redirects]]
  from = "https://sekaicouk.netlify.com"
  to = "https://sekai.co.uk"
  status = 301
  force = true
  
[[redirects]]
  from = "https://sekai.co.uk/you"
  to = "https://you.sekai.co.uk/"
  status = 301

[[redirects]]
  from = "https://sekai.co.uk/blog"
  to = "https://blog.sekai.co.uk"
  status = 301
  force = true